elements = set()
elements.add(1)
elements.add(2)
elements.add(3)
print("Create and Add elements to a set to store unique elements:", elements)
elements.remove(1)
print("Remove elements from a set:", elements)
set1 = {1, 2, 3}
set2 = {3, 4, 5}
combined_set = set1.union(set2)
print("Combine elements from two sets:", combined_set)
common_elements = set1.intersection(set2)
print("Find common elements in two sets:", common_elements)
difference_set = set1.difference(set2)
print("Find difference between two sets:", difference_set)
symmetric_difference_set = set1.symmetric_difference(set2)
print("Find elements present in either of the sets but not in their intersection:",symmetric_difference_set)
s_subset = set1.issubset(set2)
print("Check if set1 is subset of set2:", s_subset)
s_superset = set1.issuperset(set2)
print("Check if set1 is superset of set2:", s_superset)
elements.clear()
print("Clear all elements from a set:", elements)